// Code generated by go-swagger; DO NOT EDIT.

package mpp_aggregate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"github.com/JCbayfisher/swaggerTesting/models"
)

// NewPostMppaggregateParams creates a new PostMppaggregateParams object
//
// There are no default values defined in the spec.
func NewPostMppaggregateParams() PostMppaggregateParams {

	return PostMppaggregateParams{}
}

// PostMppaggregateParams contains all the bound params for the post mppaggregate operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostMppaggregate
type PostMppaggregateParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*query objects to perform on collection
	  Required: true
	  In: body
	*/
	MppAggregate *models.MppAggregate
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostMppaggregateParams() beforehand.
func (o *PostMppaggregateParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.MppAggregate
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("mppAggregate", "body", ""))
			} else {
				res = append(res, errors.NewParseError("mppAggregate", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(context.Background())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.MppAggregate = &body
			}
		}
	} else {
		res = append(res, errors.Required("mppAggregate", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
