// Code generated by go-swagger; DO NOT EDIT.

// Package restapi partD-api
//
//  Medicare Provider Project partD micro service
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /mppAPI
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
