// Code generated by go-swagger; DO NOT EDIT.

package logout

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostLogoutHandlerFunc turns a function with the right signature into a post logout handler
type PostLogoutHandlerFunc func(PostLogoutParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostLogoutHandlerFunc) Handle(params PostLogoutParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostLogoutHandler interface for that can handle valid post logout params
type PostLogoutHandler interface {
	Handle(PostLogoutParams, interface{}) middleware.Responder
}

// NewPostLogout creates a new http.Handler for the post logout operation
func NewPostLogout(ctx *middleware.Context, handler PostLogoutHandler) *PostLogout {
	return &PostLogout{Context: ctx, Handler: handler}
}

/* PostLogout swagger:route POST /logout logout postLogout

logs the user out

logs user out by expiring cookie

*/
type PostLogout struct {
	Context *middleware.Context
	Handler PostLogoutHandler
}

func (o *PostLogout) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostLogoutParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
