// Code generated by go-swagger; DO NOT EDIT.

package change_password

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostChangePasswordHandlerFunc turns a function with the right signature into a post change password handler
type PostChangePasswordHandlerFunc func(PostChangePasswordParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostChangePasswordHandlerFunc) Handle(params PostChangePasswordParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostChangePasswordHandler interface for that can handle valid post change password params
type PostChangePasswordHandler interface {
	Handle(PostChangePasswordParams, interface{}) middleware.Responder
}

// NewPostChangePassword creates a new http.Handler for the post change password operation
func NewPostChangePassword(ctx *middleware.Context, handler PostChangePasswordHandler) *PostChangePassword {
	return &PostChangePassword{Context: ctx, Handler: handler}
}

/* PostChangePassword swagger:route POST /change_password change_password postChangePassword

change a user's password

Endpoint accepts a user's email, old password, and new password to replace old password in db

*/
type PostChangePassword struct {
	Context *middleware.Context
	Handler PostChangePasswordHandler
}

func (o *PostChangePassword) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostChangePasswordParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
