// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Antibiotics antibiotics
//
// swagger:model Antibiotics
type Antibiotics struct {

	// ceftazidime
	Ceftazidime bool `json:"ceftazidime,omitempty"`

	// cost
	Cost int64 `json:"cost,omitempty"`

	// count
	Count int64 `json:"count,omitempty"`

	// geo
	Geo interface{} `json:"geo,omitempty"`
}

// Validate validates this antibiotics
func (m *Antibiotics) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this antibiotics based on context it is used
func (m *Antibiotics) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Antibiotics) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Antibiotics) UnmarshalBinary(b []byte) error {
	var res Antibiotics
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
