// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Gender gender
//
// swagger:model Gender
type Gender struct {

	// bene female count num
	BeneFemaleCountNum int64 `json:"bene_female_count_num,omitempty"`

	// bene male count num
	BeneMaleCountNum int64 `json:"bene_male_count_num,omitempty"`

	// city
	City string `json:"city,omitempty"`

	// coordinates
	Coordinates []float64 `json:"coordinates"`

	// female percentage
	FemalePercentage float64 `json:"female_percentage,omitempty"`

	// male percentage
	MalePercentage float64 `json:"male_percentage,omitempty"`

	// npi
	Npi string `json:"npi,omitempty"`

	// specialty
	Specialty string `json:"specialty,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// street
	Street string `json:"street,omitempty"`

	// total bene count num
	TotalBeneCountNum int64 `json:"total_bene_count_num,omitempty"`
}

// Validate validates this gender
func (m *Gender) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this gender based on context it is used
func (m *Gender) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Gender) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Gender) UnmarshalBinary(b []byte) error {
	var res Gender
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
