// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Opioids opioids
//
// swagger:model Opioids
type Opioids struct {

	// count
	Count int64 `json:"count,omitempty"`

	// geo
	Geo interface{} `json:"geo,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// la count
	LaCount int64 `json:"laCount,omitempty"`

	// la prescriber rate
	LaPrescriberRate float64 `json:"laPrescriberRate,omitempty"`

	// prescriber rate
	PrescriberRate float64 `json:"prescriberRate,omitempty"`
}

// Validate validates this opioids
func (m *Opioids) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this opioids based on context it is used
func (m *Opioids) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Opioids) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Opioids) UnmarshalBinary(b []byte) error {
	var res Opioids
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
