// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PhysicianAddress physician address
//
// swagger:model PhysicianAddress
type PhysicianAddress struct {

	// coordinates
	Coordinates []float64 `json:"coordinates"`

	// npi
	Npi string `json:"npi,omitempty"`

	// street1
	Street1 string `json:"street1,omitempty"`
}

// Validate validates this physician address
func (m *PhysicianAddress) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this physician address based on context it is used
func (m *PhysicianAddress) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PhysicianAddress) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PhysicianAddress) UnmarshalBinary(b []byte) error {
	var res PhysicianAddress
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
